# Autogenerated wrapper script for PangolinCApi_jll for x86_64-linux-gnu-cxx11
export libpangolin_c_api

using Pangolin_jll
JLLWrappers.@generate_wrapper_header("PangolinCApi")
JLLWrappers.@declare_library_product(libpangolin_c_api, "libpangolin_c_api.so")
function __init__()
    JLLWrappers.@generate_init_header(Pangolin_jll)
    JLLWrappers.@init_library_product(
        libpangolin_c_api,
        "lib/libpangolin_c_api.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
